# Generated by Django 2.1.5 on 2019-01-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_value', models.IntegerField()),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('text', models.CharField(max_length=30)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_test', to='WIMPsite.ChemicalTest')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_run', models.DateTimeField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledtest',
            name='test_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='WIMPsite.TestStrip'),
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strip', to='WIMPsite.TestStrip'),
        ),
    ]
