# Generated by Django 2.1.5 on 2019-01-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicaltest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests',
                                    to='WIMPsite.TestStrip'),
        ),
        migrations.AlterField(
            model_name='color',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors',
                                    to='WIMPsite.ChemicalTest'),
        ),
        migrations.AlterField(
            model_name='scheduledtest',
            name='test_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strip',
                                    to='WIMPsite.TestStrip'),
        ),
    ]
