# Generated by Django 2.1.5 on 2019-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0003_scheduledtest_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='unit_value',
            field=models.FloatField(),
        ),
    ]
