# Generated by Django 2.1.5 on 2019-01-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0004_auto_20190125_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('chemical_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results',
                                                    to='WIMPsite.ChemicalTest')),
                ('color_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results',
                                                  to='WIMPsite.Color')),
            ],
        ),
    ]
