# Generated by Django 2.1.5 on 2019-02-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0006_testresult_time_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('temp', models.FloatField()),
            ],
        ),
    ]
