# Generated by Django 2.1.5 on 2019-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0007_tempresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicaltest',
            name='region_x1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='region_x2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='region_y1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='region_y2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
