# Generated by Django 2.1.5 on 2019-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0008_auto_20190215_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicaltest',
            name='region_x1',
        ),
        migrations.RemoveField(
            model_name='chemicaltest',
            name='region_x2',
        ),
        migrations.RemoveField(
            model_name='chemicaltest',
            name='region_y1',
        ),
        migrations.RemoveField(
            model_name='chemicaltest',
            name='region_y2',
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='test_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
