# Generated by Django 2.1.5 on 2019-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0009_auto_20190305_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtest',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
    ]
