# Generated by Django 2.1.5 on 2019-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WIMPsite', '0012_color_invert_color_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='invert_color_match',
        ),
        migrations.AddField(
            model_name='chemicaltest',
            name='invert_color_match',
            field=models.BooleanField(default=False),
        ),
    ]
